/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'OverlapPingReq'
 * message type.
 */

public class OverlapPingReq extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 4;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 7;

    /** Create a new OverlapPingReq of size 4. */
    public OverlapPingReq() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new OverlapPingReq of the given data_length. */
    public OverlapPingReq(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new OverlapPingReq with the given data_length
     * and base offset.
     */
    public OverlapPingReq(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new OverlapPingReq using the given byte array
     * as backing store.
     */
    public OverlapPingReq(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new OverlapPingReq using the given byte array
     * as backing store, with the given base offset.
     */
    public OverlapPingReq(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new OverlapPingReq using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public OverlapPingReq(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new OverlapPingReq embedded in the given message
     * at the given base offset.
     */
    public OverlapPingReq(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new OverlapPingReq embedded in the given message
     * at the given base offset and length.
     */
    public OverlapPingReq(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <OverlapPingReq> \n";
      try {
        s += "  [prot=0x"+Long.toHexString(get_prot())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [source=0x"+Long.toHexString(get_source())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: prot
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'prot' is signed (false).
     */
    public static boolean isSigned_prot() {
        return false;
    }

    /**
     * Return whether the field 'prot' is an array (false).
     */
    public static boolean isArray_prot() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'prot'
     */
    public static int offset_prot() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'prot'
     */
    public static int offsetBits_prot() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'prot'
     */
    public int get_prot() {
        return (int)getUIntBEElement(offsetBits_prot(), 16);
    }

    /**
     * Set the value of the field 'prot'
     */
    public void set_prot(int value) {
        setUIntBEElement(offsetBits_prot(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'prot'
     */
    public static int size_prot() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'prot'
     */
    public static int sizeBits_prot() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: source
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'source' is signed (false).
     */
    public static boolean isSigned_source() {
        return false;
    }

    /**
     * Return whether the field 'source' is an array (false).
     */
    public static boolean isArray_source() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'source'
     */
    public static int offset_source() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'source'
     */
    public static int offsetBits_source() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'source'
     */
    public int get_source() {
        return (int)getUIntBEElement(offsetBits_source(), 16);
    }

    /**
     * Set the value of the field 'source'
     */
    public void set_source(int value) {
        setUIntBEElement(offsetBits_source(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'source'
     */
    public static int size_source() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'source'
     */
    public static int sizeBits_source() {
        return 16;
    }

}
