/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'FloodMsg'
 * message type.
 */

public class FloodMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 26;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 2;

    /** Create a new FloodMsg of size 26. */
    public FloodMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new FloodMsg of the given data_length. */
    public FloodMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new FloodMsg with the given data_length
     * and base offset.
     */
    public FloodMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new FloodMsg using the given byte array
     * as backing store.
     */
    public FloodMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new FloodMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public FloodMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new FloodMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public FloodMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new FloodMsg embedded in the given message
     * at the given base offset.
     */
    public FloodMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new FloodMsg embedded in the given message
     * at the given base offset and length.
     */
    public FloodMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <FloodMsg> \n";
      try {
        s += "  [sources=";
        for (int i = 0; i < 10; i++) {
          s += "0x"+Long.toHexString(getElement_sources(i) & 0xffff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [temp=0x"+Long.toHexString(get_temp())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [hum=0x"+Long.toHexString(get_hum())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [wind=0x"+Long.toHexString(get_wind())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: sources
    //   Field type: int[], unsigned
    //   Offset (bits): 0
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'sources' is signed (false).
     */
    public static boolean isSigned_sources() {
        return false;
    }

    /**
     * Return whether the field 'sources' is an array (true).
     */
    public static boolean isArray_sources() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'sources'
     */
    public static int offset_sources(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 10) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'sources'
     */
    public static int offsetBits_sources(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 10) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return offset;
    }

    /**
     * Return the entire array 'sources' as a int[]
     */
    public int[] get_sources() {
        int[] tmp = new int[10];
        for (int index0 = 0; index0 < numElements_sources(0); index0++) {
            tmp[index0] = getElement_sources(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'sources' from the given int[]
     */
    public void set_sources(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_sources(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'sources'
     */
    public int getElement_sources(int index1) {
        return (int)getUIntBEElement(offsetBits_sources(index1), 16);
    }

    /**
     * Set an element of the array 'sources'
     */
    public void setElement_sources(int index1, int value) {
        setUIntBEElement(offsetBits_sources(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'sources'
     */
    public static int totalSize_sources() {
        return (160 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'sources'
     */
    public static int totalSizeBits_sources() {
        return 160;
    }

    /**
     * Return the size, in bytes, of each element of the array 'sources'
     */
    public static int elementSize_sources() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'sources'
     */
    public static int elementSizeBits_sources() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'sources'
     */
    public static int numDimensions_sources() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'sources'
     */
    public static int numElements_sources() {
        return 10;
    }

    /**
     * Return the number of elements in the array 'sources'
     * for the given dimension.
     */
    public static int numElements_sources(int dimension) {
      int array_dims[] = { 10,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: temp
    //   Field type: int, unsigned
    //   Offset (bits): 160
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'temp' is signed (false).
     */
    public static boolean isSigned_temp() {
        return false;
    }

    /**
     * Return whether the field 'temp' is an array (false).
     */
    public static boolean isArray_temp() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'temp'
     */
    public static int offset_temp() {
        return (160 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'temp'
     */
    public static int offsetBits_temp() {
        return 160;
    }

    /**
     * Return the value (as a int) of the field 'temp'
     */
    public int get_temp() {
        return (int)getUIntBEElement(offsetBits_temp(), 16);
    }

    /**
     * Set the value of the field 'temp'
     */
    public void set_temp(int value) {
        setUIntBEElement(offsetBits_temp(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'temp'
     */
    public static int size_temp() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'temp'
     */
    public static int sizeBits_temp() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: hum
    //   Field type: int, unsigned
    //   Offset (bits): 176
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'hum' is signed (false).
     */
    public static boolean isSigned_hum() {
        return false;
    }

    /**
     * Return whether the field 'hum' is an array (false).
     */
    public static boolean isArray_hum() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'hum'
     */
    public static int offset_hum() {
        return (176 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'hum'
     */
    public static int offsetBits_hum() {
        return 176;
    }

    /**
     * Return the value (as a int) of the field 'hum'
     */
    public int get_hum() {
        return (int)getUIntBEElement(offsetBits_hum(), 16);
    }

    /**
     * Set the value of the field 'hum'
     */
    public void set_hum(int value) {
        setUIntBEElement(offsetBits_hum(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'hum'
     */
    public static int size_hum() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'hum'
     */
    public static int sizeBits_hum() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: wind
    //   Field type: int, unsigned
    //   Offset (bits): 192
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'wind' is signed (false).
     */
    public static boolean isSigned_wind() {
        return false;
    }

    /**
     * Return whether the field 'wind' is an array (false).
     */
    public static boolean isArray_wind() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'wind'
     */
    public static int offset_wind() {
        return (192 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'wind'
     */
    public static int offsetBits_wind() {
        return 192;
    }

    /**
     * Return the value (as a int) of the field 'wind'
     */
    public int get_wind() {
        return (int)getUIntBEElement(offsetBits_wind(), 16);
    }

    /**
     * Set the value of the field 'wind'
     */
    public void set_wind(int value) {
        setUIntBEElement(offsetBits_wind(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'wind'
     */
    public static int size_wind() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'wind'
     */
    public static int sizeBits_wind() {
        return 16;
    }

}
