/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'RadioCountMsg'
 * message type.
 */

public class RadioCountMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 12;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 6;

    /** Create a new RadioCountMsg of size 12. */
    public RadioCountMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new RadioCountMsg of the given data_length. */
    public RadioCountMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RadioCountMsg with the given data_length
     * and base offset.
     */
    public RadioCountMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RadioCountMsg using the given byte array
     * as backing store.
     */
    public RadioCountMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RadioCountMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public RadioCountMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RadioCountMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public RadioCountMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RadioCountMsg embedded in the given message
     * at the given base offset.
     */
    public RadioCountMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RadioCountMsg embedded in the given message
     * at the given base offset and length.
     */
    public RadioCountMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <RadioCountMsg> \n";
      try {
        s += "  [temp=0x"+Long.toHexString(get_temp())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [hum=0x"+Long.toHexString(get_hum())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [wind=0x"+Long.toHexString(get_wind())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: temp
    //   Field type: long, unsigned
    //   Offset (bits): 0
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'temp' is signed (false).
     */
    public static boolean isSigned_temp() {
        return false;
    }

    /**
     * Return whether the field 'temp' is an array (false).
     */
    public static boolean isArray_temp() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'temp'
     */
    public static int offset_temp() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'temp'
     */
    public static int offsetBits_temp() {
        return 0;
    }

    /**
     * Return the value (as a long) of the field 'temp'
     */
    public long get_temp() {
        return (long)getUIntBEElement(offsetBits_temp(), 32);
    }

    /**
     * Set the value of the field 'temp'
     */
    public void set_temp(long value) {
        setUIntBEElement(offsetBits_temp(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'temp'
     */
    public static int size_temp() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'temp'
     */
    public static int sizeBits_temp() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: hum
    //   Field type: long, unsigned
    //   Offset (bits): 32
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'hum' is signed (false).
     */
    public static boolean isSigned_hum() {
        return false;
    }

    /**
     * Return whether the field 'hum' is an array (false).
     */
    public static boolean isArray_hum() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'hum'
     */
    public static int offset_hum() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'hum'
     */
    public static int offsetBits_hum() {
        return 32;
    }

    /**
     * Return the value (as a long) of the field 'hum'
     */
    public long get_hum() {
        return (long)getUIntBEElement(offsetBits_hum(), 32);
    }

    /**
     * Set the value of the field 'hum'
     */
    public void set_hum(long value) {
        setUIntBEElement(offsetBits_hum(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'hum'
     */
    public static int size_hum() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'hum'
     */
    public static int sizeBits_hum() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: wind
    //   Field type: long, unsigned
    //   Offset (bits): 64
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'wind' is signed (false).
     */
    public static boolean isSigned_wind() {
        return false;
    }

    /**
     * Return whether the field 'wind' is an array (false).
     */
    public static boolean isArray_wind() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'wind'
     */
    public static int offset_wind() {
        return (64 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'wind'
     */
    public static int offsetBits_wind() {
        return 64;
    }

    /**
     * Return the value (as a long) of the field 'wind'
     */
    public long get_wind() {
        return (long)getUIntBEElement(offsetBits_wind(), 32);
    }

    /**
     * Set the value of the field 'wind'
     */
    public void set_wind(long value) {
        setUIntBEElement(offsetBits_wind(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'wind'
     */
    public static int size_wind() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'wind'
     */
    public static int sizeBits_wind() {
        return 32;
    }

}
