/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'PathMsg'
 * message type.
 */

public class PathMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 4;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 6;

    /** Create a new PathMsg of size 4. */
    public PathMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new PathMsg of the given data_length. */
    public PathMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PathMsg with the given data_length
     * and base offset.
     */
    public PathMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PathMsg using the given byte array
     * as backing store.
     */
    public PathMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PathMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public PathMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PathMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public PathMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PathMsg embedded in the given message
     * at the given base offset.
     */
    public PathMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new PathMsg embedded in the given message
     * at the given base offset and length.
     */
    public PathMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <PathMsg> \n";
      try {
        s += "  [path=0x"+Long.toHexString(get_path())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: path
    //   Field type: int, signed
    //   Offset (bits): 0
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'path' is signed (true).
     */
    public static boolean isSigned_path() {
        return true;
    }

    /**
     * Return whether the field 'path' is an array (false).
     */
    public static boolean isArray_path() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'path'
     */
    public static int offset_path() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'path'
     */
    public static int offsetBits_path() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'path'
     */
    public int get_path() {
        return (int)getSIntBEElement(offsetBits_path(), 32);
    }

    /**
     * Set the value of the field 'path'
     */
    public void set_path(int value) {
        setSIntBEElement(offsetBits_path(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'path'
     */
    public static int size_path() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'path'
     */
    public static int sizeBits_path() {
        return 32;
    }

}
